/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbotubes;
import Logic.*;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author HUMAIDI
 */
public class beli extends javax.swing.JPanel {

    /**
     * Creates new form beli
     */
    user pengguna;
    public beli(user temp) {
        initComponents();
        pengguna = temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(560, 460));
        setLayout(null);

        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(60, 57, 380, 45);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbotubes/images/bbeli.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(50, 200, 54, 38);

        jComboBox1.setMaximumRowCount(5);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10.000 - Rp.11.000", "20.000 - Rp.22.000", "50.000 - Rp.55.000", "100.000 - Rp.110.000" }));
        add(jComboBox1);
        jComboBox1.setBounds(48, 145, 403, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbotubes/images/belipanel.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String no = (String)jComboBox1.getSelectedItem();
        HashMap<String, Integer> daftar = new HashMap<>();
        daftar.put("10.000 - Rp.11.000", 10000);
        daftar.put("20.000 - Rp.22.000", 20000);
        daftar.put("50.000 - Rp.55.000", 50000);
        daftar.put("100.000 - Rp.110.000", 100000);
        String id = jTextField1.getText();
        try {
            String kode = pengguna.beli(id, daftar.get(no));
            if(kode != null){
                JOptionPane.showMessageDialog(this,"Token anda : "+kode);
            }
            else{
                JOptionPane.showMessageDialog(this, "Pembelian Gagal!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Databasee Error!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver Error!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
