/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbotubes;
import Logic.*;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author HUMAIDI
 */
public class history extends javax.swing.JPanel {

    /**
     * Creates new form history
     */
    user pengguna;
    Vector<Vector<String>> h;
    Vector<String> a;
    public void refresh(){
        try {
            h = pengguna.history();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Databasee Error!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            h,
            a
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }
    public history(user temp){
        pengguna = temp;
        a = new Vector<>();
        a.add("No Transaksi");
        a.add("Tanggal");
        a.add("ID Pelanggan");
        a.add("Total");
        try {
            h = pengguna.history();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Driver not found!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Databasee Error!",
                "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        initComponents(temp);
        refresh();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(user temp) {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(560, 460));
       
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            h,
            a
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 560, 460);
    }// </editor-fold>                        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(560, 460));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Transaksi", "Tanggal", "ID Pelanggan", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 560, 460);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
