/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbotubes;
import Logic.*;
/**
 *
 * @author HUMAIDI
 */
public class home extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public home(user temp) {
        initComponents();
        nama.setText(temp.user+".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nama = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(560, 460));
        setLayout(null);

        nama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        nama.setForeground(new java.awt.Color(255, 255, 255));
        nama.setToolTipText("");
        add(nama);
        nama.setBounds(220, 20, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbotubes/images/homepanel.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 460);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nama;
    // End of variables declaration//GEN-END:variables
}
